version: "3"

services: 
    web:
        container_name: exampleapp
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mymongodb
        image: mongo
        ports:
            - 17027:17027
        logging: 
            driver: none
